$wallpaper = /home/developer/Pictures/Wallpapers/goku.jpg
$background = rgb(02040A)
$foreground = rgb(ABFFA3)
$color0 = rgb(04060C)
$color1 = rgb(3F8BC4)
$color2 = rgb(A38257)
$color3 = rgb(7A1610)
$color4 = rgb(589724)
$color5 = rgb(E15737)
$color6 = rgb(8FE488)
$color7 = rgb(A4FB9C)
$color8 = rgb(58A854)
$color9 = rgb(3F8BC4)
$color10 = rgb(A38257)
$color11 = rgb(7A1610)
$color12 = rgb(589724)
$color13 = rgb(E15737)
$color14 = rgb(8FE488)
$color15 = rgb(C9F5C5)
