$wallpaper = /home/developer/Pictures/Wallpapers/estilo-matrix.jpg
$background = rgb(020102)
$foreground = rgb(7AB19F)
$color0 = rgb(020102)
$color1 = rgb(414145)
$color2 = rgb(3D483C)
$color3 = rgb(4B4256)
$color4 = rgb(525659)
$color5 = rgb(536678)
$color6 = rgb(447166)
$color7 = rgb(609685)
$color8 = rgb(34695A)
$color9 = rgb(414145)
$color10 = rgb(3D483C)
$color11 = rgb(4B4256)
$color12 = rgb(525659)
$color13 = rgb(536678)
$color14 = rgb(447166)
$color15 = rgb(A7C2BA)
