[global]
background = "{{background}}DD"
foreground = "{{foreground}}"
frame_color = "{{color6}}"
separator_color = "{{color8}}"

[urgency_low]
background = "{{background}}DD"
foreground = "{{foreground}}"
frame_color = "{{color8}}"

[urgency_normal]
background = "{{background}}DD"
foreground = "{{foreground}}"
frame_color = "{{color6}}"

[urgency_critical]
background = "{{background}}cc"
foreground = "{{foreground}}"
frame_color = "{{color9}}"
